/* Those tables were generated with a online generator, so the classNames are autogenerated names*/
import React from 'react'
export default function lists() {
  function hideCols(event) {
    const btnID = event.target.id
    const btn = document.getElementById(btnID)
    const tableID = btnID.slice(0, -9)
    const table = document.getElementById(tableID)
    const col = btnID.charAt(10)
    const tr = table.getElementsByTagName("tr")

    for (let i = 0; i < tr.length; i++) {
      if (i === 0) {
        const th = tr[i].getElementsByTagName("th")[col]
        if (th.style.display === "") {
          th.style.display = "none"
        } else if (th.style.display === "none") {
          th.style.display = ""
        }
      }
      else {
        const td = tr[i].getElementsByTagName("td")[col - 1]
        if (td.style.display === "") {
          td.style.display = "none"
          btn.style.backgroundColor = "rgb(245,245,245)"
          btn.style.color = "#000"
        } else if (td.style.display === "none") {
          td.style.display = ""
          btn.style.backgroundColor = "#000"
          btn.style.color = "#fff"
        }
      }
    }
  }

  function filterTableRows(event) {
    const inputID = event.target.id
    const input = document.getElementById(inputID)
    const filter = input.value.toLowerCase()
    const tableID = event.target.id.slice(0, -12)
    const table = document.getElementById(tableID)
    const tr = table.getElementsByTagName("tr")

    for (let i = 2; i < tr.length; i++) {
      const th = tr[i].getElementsByTagName("th")[0];
      const txtValue = th.innerText;
      if (txtValue.toLowerCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
  return (
    <details style={{ marginBottom: "3%" }}>
      <summary>
        Lists
      </summary>
      <div class="table-buttons">
        <button class="table-btn" id="table1-col1-btn" onClick={hideCols}>ArrayList</button>
        <button class="table-btn" id="table1-col2-btn" onClick={hideCols}>AttributeList</button>
        <button class="table-btn" id="table1-col3-btn" onClick={hideCols}>LinkedList</button>
        <button class="table-btn" id="table1-col4-btn" onClick={hideCols}>Stack</button>
        <button class="table-btn" id="table1-col5-btn" onClick={hideCols}>Vector</button>
      </div>
      <table id="table1" class="tg">
        <colgroup>
          <col id="header-vertical" style={{ width: "20%" }} />
          <col id="arraylist" />
          <col id="attributelist" />
          <col id="linkedlist" />
          <col id="stack" />
          <col id="vector" />
        </colgroup>
        <thead>
          <tr class="header-desktop">
            <th class="tg-j6zm">Methods / DataStructure</th>
            <th class="tg-j6zm">ArrayList</th>
            <th class="tg-j6zm">AttributeList</th>
            <th class="tg-j6zm">LinkedList</th>
            <th class="tg-j6zm">Stack</th>
            <th class="tg-j6zm">Vector</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th class="tg-fymr"><input id="table1-filterInput" onChange={filterTableRows} type="text" placeholder="search method" /></th>
            <td class="tg-j6zm">Joule</td>
            <td class="tg-j6zm">Joule</td>
            <td class="tg-j6zm">Joule</td>
            <td class="tg-j6zm">Joule</td>
            <td class="tg-j6zm">Joule</td>
          </tr>
          <tr>
            <th class="tg-7zrl">add</th>
            <td class="tg-rlbz">0,9773</td>
            <td class="tg-v8wt">1.1510</td>
            <td class="tg-075i">1.8016</td>
            <td class="tg-lcw7">1.5659</td>
            <td class="tg-mukt">1.5177</td>
          </tr>
          <tr>
            <th class="tg-7zrl">addAll</th>
            <td class="tg-mukt">1.3353</td>
            <td class="tg-rlbz">1.0492</td>
            <td class="tg-rlbz">1.1043</td>
            <td class="tg-v8wt">1.1015</td>
            <td class="tg-dzo9">1.7903</td>
          </tr>
          <tr>
            <th class="tg-7zrl">addAlli</th>
            <td class="tg-dc3p">1.7855</td>
            <td class="tg-mukt">1.6035</td>
            <td class="tg-39dj">1.7272</td>
            <td class="tg-v8wt">1.2962</td>
            <td class="tg-h4gw">1.6268</td>
          </tr>
          <tr>
            <th class="tg-7zrl">addl</th>
            <td class="tg-dc3p">1,7125</td>
            <td class="tg-ry5z">1.3849</td>
            <td class="tg-39dj">1.6404</td>
            <td class="tg-lcw7">1.5287</td>
            <td class="tg-mukt">1.4554</td>
          </tr>
          <tr>
            <th class="tg-7zrl">clear</th>
            <td class="tg-rlbz">1.1284</td>
            <td class="tg-v8wt">1.2409</td>
            <td class="tg-39dj">1.6497</td>
            <td class="tg-39dj">1.6199</td>
            <td class="tg-rlbz">1.0574</td>
          </tr>
          <tr>
            <th class="tg-7zrl">contains</th>
            <td class="tg-39dj">2.7568</td>
            <td class="tg-mukt">2.4228</td>
            <td class="tg-075i">3.1552</td>
            <td class="tg-rlbz">2.0128</td>
            <td class="tg-v8wt">2.1558</td>
          </tr>
          <tr>
            <th class="tg-7zrl">containsAll</th>
            <td class="tg-bvjv">1.5993</td>
            <td class="tg-x91g">1.8053</td>
            <td class="tg-075i">2.2887</td>
            <td class="tg-rlbz">1.2054</td>
            <td class="tg-mukt">1.5091</td>
          </tr>
          <tr>
            <th class="tg-7zrl">get</th>
            <td class="tg-39dj">2.2029</td>
            <td class="tg-rlbz">1.1171</td>
            <td class="tg-x91g">2.0168</td>
            <td class="tg-h4gw">1.8956</td>
            <td class="tg-ry5z">1.4978</td>
          </tr>
          <tr>
            <th class="tg-7zrl">indexOf</th>
            <td class="tg-ry5z">1.4447</td>
            <td class="tg-x91g">2.0325</td>
            <td class="tg-075i">2.6289</td>
            <td class="tg-bvjv">1.8090</td>
            <td class="tg-h4gw">2.0788</td>
          </tr>
          <tr>
            <th class="tg-7zrl">iterateAll</th>
            <td class="tg-39dj">2.0701</td>
            <td class="tg-rlbz">1.0473</td>
            <td class="tg-075i">2.6401</td>
            <td class="tg-bvjv">1.6036</td>
            <td class="tg-v8wt">1.1336</td>
          </tr>
          <tr>
            <th class="tg-7zrl">iterator</th>
            <td class="tg-j8j9">1.4893</td>
            <td class="tg-rlbz">1.1589</td>
            <td class="tg-bvjv">1.7666</td>
            <td class="tg-bbs6">2.1895</td>
            <td class="tg-bvjv">1.6505</td>
          </tr>
          <tr>
            <th class="tg-7zrl">lastIndexOf</th>
            <td class="tg-2rmf">1.7750</td>
            <td class="tg-mukt">1.7666</td>
            <td class="tg-075i">2.5019</td>
            <td class="tg-rlbz">1.2260</td>
            <td class="tg-ugrm">1.2296</td>
          </tr>
          <tr>
            <th class="tg-7zrl">listIterator</th>
            <td class="tg-j8j9">1.4457</td>
            <td class="tg-h4gw">1.6190</td>
            <td class="tg-075i">2.5003</td>
            <td class="tg-bvjv">1.6354</td>
            <td class="tg-ugrm">1.2746</td>
          </tr>
          <tr>
            <th class="tg-7zrl">listIteratori</th>
            <td class="tg-2rmf">1.7356</td>
            <td class="tg-rlbz">1.5552</td>
            <td class="tg-075i">2.1996</td>
            <td class="tg-h4gw">1.8799</td>
            <td class="tg-x91g">1.7545</td>
          </tr>
          <tr>
            <th class="tg-7zrl">remove</th>
            <td class="tg-rlbz">1.1308</td>
            <td class="tg-mukt">1.4480</td>
            <td class="tg-lcw7">1.6924</td>
            <td class="tg-v8wt">1.2663</td>
            <td class="tg-x91g">1.4973</td>
          </tr>
          <tr>
            <th class="tg-7zrl">removeAll</th>
            <td class="tg-dzo9">8.0905</td>
            <td class="tg-h4gw">7.8108</td>
            <td class="tg-075i">8.3150</td>
            <td class="tg-v8wt">7.3824</td>
            <td class="tg-ugrm">7.1281</td>
          </tr>
          <tr>
            <th class="tg-7zrl">removei</th>
            <td class="tg-39dj">1.9135</td>
            <td class="tg-rlbz">1.3534</td>
            <td class="tg-mukt">1.7174</td>
            <td class="tg-ry5z">1.5850</td>
            <td class="tg-v8wt">1.5486</td>
          </tr>
          <tr>
            <th class="tg-7zrl">reatinAll</th>
            <td class="tg-mukt">2.0737</td>
            <td class="tg-bvjv">2.7845</td>
            <td class="tg-v8wt">2.5982</td>
            <td class="tg-mukt">2.7635</td>
            <td class="tg-075i">3.4019</td>
          </tr>
          <tr>
            <th class="tg-7zrl">set</th>
            <td class="tg-rlbz">0,9476</td>
            <td class="tg-h4gw">1.5943</td>
            <td class="tg-075i">2.0474</td>
            <td class="tg-mukt">1.4938</td>
            <td class="tg-mukt">1.4957</td>
          </tr>
          <tr>
            <th class="tg-7zrl">sublist</th>
            <td class="tg-v8wt">1,1308</td>
            <td class="tg-x91g">1.6021</td>
            <td class="tg-075i">1.8457</td>
            <td class="tg-dzo9">1.7082</td>
            <td class="tg-ugrm">0,9414</td>
          </tr>
          <tr>
            <th class="tg-7zrl">toArray</th>
            <td class="tg-mukt">1.6418</td>
            <td class="tg-ugrm">1.5024</td>
            <td class="tg-x91g">1.6739</td>
            <td class="tg-ry5z">1.5694</td>
            <td class="tg-075i">2.0213</td>
          </tr>
        </tbody>
      </table>
    </details>
  )
}
