/* The tables where generated with an online generator, there the classnames are autogenerated-names */
import React from 'react'

export default function Maps() {
    function hideCols(event) {
        const btnID = event.target.id
        const btn = document.getElementById(btnID)
        const tableID = btnID.slice(0, -9)
        const table = document.getElementById(tableID)
        const col = btnID.charAt(10)
        const tr = table.getElementsByTagName("tr")

        for (let i = 0; i < tr.length; i++) {
            if (i === 0) {
                const th = tr[i].getElementsByTagName("th")[col]
                if (th.style.display === "") {
                    th.style.display = "none"
                } else if (th.style.display === "none") {
                    th.style.display = ""
                }
            }
            else {
                const td = tr[i].getElementsByTagName("td")[col - 1]
                if (td.style.display === "") {
                    td.style.display = "none"
                    btn.style.backgroundColor = "rgb(245,245,245)"
                    btn.style.color = "#000"
                } else if (td.style.display === "none") {
                    td.style.display = ""
                    btn.style.backgroundColor = "#000"
                    btn.style.color = "#fff"
                }
            }
        }
    }

    function filterTableRows(event) {
        const inputID = event.target.id
        const input = document.getElementById(inputID)
        const filter = input.value.toLowerCase()
        const tableID = event.target.id.slice(0, -12)
        const table = document.getElementById(tableID)
        const tr = table.getElementsByTagName("tr")

        for (let i = 2; i < tr.length; i++) {
            const th = tr[i].getElementsByTagName("th")[0];
            const txtValue = th.innerText;
            if (txtValue.toLowerCase().indexOf(filter) > -1) {
                tr[i].style.display = "";
            } else {
                tr[i].style.display = "none";
            }
        }
    }
    return (
        <details style={{ marginBottom: "3%" }}>
            <summary>Maps</summary>
            <div class="table-buttons">
                <button class="table-btn" id="table3-col1-btn" onClick={hideCols}>Hashmap</button>
                <button class="table-btn" id="table3-col2-btn" onClick={hideCols}>HashTable</button>
                <button class="table-btn" id="table3-col3-btn" onClick={hideCols}>LinkedHashMap</button>
                <button class="table-btn" id="table3-col4-btn" onClick={hideCols}>TreeMap</button>
            </div>
            <table id="table3" class="tg">
                <colgroup>
                    <col id="header-vertical3" style={{ width: "20%" }} />
                    <col id="hashmap" />
                    <col id="hashtable" />
                    <col id="linkedhashmap" />
                    <col id="treemap" />
                </colgroup>
                <thead>
                    <tr>
                        <th class="tg-0thz">Methods / DataStructures</th>
                        <th class="tg-0thz">HashMap</th>
                        <th class="tg-0thz">HashTable</th>
                        <th class="tg-0thz">LinkedHashMap</th>
                        <th class="tg-0thz">TreeMap</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th class="tg-fymr"><input id="table3-filterInput" onChange={filterTableRows} type="text" placeholder="search method" /></th>
                        <td class="tg-0thz">Joule</td>
                        <td class="tg-0thz">Joule</td>
                        <td class="tg-0thz">Joule</td>
                        <td class="tg-0thz">Joule</td>
                    </tr>
                    <tr>
                        <th class="tg-za14">clear</th>
                        <td class="tg-05tu">1.8395</td>
                        <td class="tg-5fgp">1.5761</td>
                        <td class="tg-5fgp">1.5025</td>
                        <td class="tg-84pi">1.6706</td>
                    </tr>
                    <tr>
                        <th class="tg-za14">containsKey</th>
                        <td class="tg-rovy">2.1343</td>
                        <td class="tg-84pi">1.8582</td>
                        <td class="tg-84pi">1.8726</td>
                        <td class="tg-05tu">1.9452</td>
                    </tr>
                    <tr>
                        <th class="tg-za14">containsValue</th>
                        <td class="tg-5m3m">8.3615</td>
                        <td class="tg-kcqh">8.4957</td>
                        <td class="tg-5fgp">6.1326</td>
                        <td class="tg-05tu">9.1771</td>
                    </tr>
                    <tr>
                        <th class="tg-za14">entrySet</th>
                        <td class="tg-lejy">1.8531</td>
                        <td class="tg-rovy">2.1332</td>
                        <td class="tg-84pi">1.8362</td>
                        <td class="tg-d0k2">2.1617</td>
                    </tr>
                    <tr>
                        <th class="tg-za14">get</th>
                        <td class="tg-5m3m">1.8120</td>
                        <td class="tg-5fgp">1.4071</td>
                        <td class="tg-ivaq">1.8252</td>
                        <td class="tg-j7z7">2.2331</td>
                    </tr>
                    <tr>
                        <th class="tg-za14">iterateAll</th>
                        <td class="tg-j7z7">2.6673</td>
                        <td class="tg-5fgp">1.5343</td>
                        <td class="tg-84pi">1.6462</td>
                        <td class="tg-kcqh">1.9122</td>
                    </tr>
                    <tr>
                        <th class="tg-za14">keySet</th>
                        <td class="tg-84pi">1.6813</td>
                        <td class="tg-d0k2">2.2226</td>
                        <td class="tg-05tu">1.8328</td>
                        <td class="tg-rovy">2.1680</td>
                    </tr>
                    <tr>
                        <th class="tg-za14">put
                        </th>
                        <td class="tg-d0k2">2.4628</td>
                        <td class="tg-5fgp">1.3123</td>
                        <td class="tg-05tu">2.0338</td>
                        <td class="tg-5fgp">1.4355</td>
                    </tr>
                    <tr>
                        <th class="tg-za14">putAll</th>
                        <td class="tg-n78w">1.7564</td>
                        <td class="tg-84pi">1.5949</td>
                        <td class="tg-05tu">1.8608</td>
                        <td class="tg-kcqh">1.8914</td>
                    </tr>
                    <tr>
                        <th class="tg-za14">remove</th>
                        <td class="tg-kcqh">1.9256</td>
                        <td class="tg-5fgp">1.6067</td>
                        <td class="tg-d0k2">2.2300</td>
                        <td class="tg-84pi">1.8133</td>
                    </tr>
                    <tr>
                        <th class="tg-za14">values</th>
                        <td class="tg-j7z7">2.5755</td>
                        <td class="tg-rovy">2.2266</td>
                        <td class="tg-05tu">2.2009</td>
                        <td class="tg-5fgp">1.4467</td>
                    </tr>
                </tbody>
            </table>
        </details>
    )
}
