/* The tables where generated with an online generator, there the classnames are autogenerated-names */
import React from 'react'

export default function Sets() {
  function hideCols(event) {
    const btnID = event.target.id
    const btn = document.getElementById(btnID)
    const tableID = btnID.slice(0, -9)
    const table = document.getElementById(tableID)
    const col = btnID.charAt(10)
    const tr = table.getElementsByTagName("tr")

    for (let i = 0; i < tr.length; i++) {
      if (i === 0) {
        const th = tr[i].getElementsByTagName("th")[col]
        if (th.style.display === "") {
          th.style.display = "none"
        } else if (th.style.display === "none") {
          th.style.display = ""
        }
      }
      else {
        const td = tr[i].getElementsByTagName("td")[col - 1]
        if (td.style.display === "") {
          td.style.display = "none"
          btn.style.backgroundColor = "rgb(245,245,245)"
          btn.style.color = "#000"
        } else if (td.style.display === "none") {
          td.style.display = ""
          btn.style.backgroundColor = "#000"
          btn.style.color = "#fff"
        }
      }

    }
  }

  function filterTableRows(event) {
    const inputID = event.target.id
    const input = document.getElementById(inputID)
    const filter = input.value.toLowerCase()
    const tableID = event.target.id.slice(0, -12)
    const table = document.getElementById(tableID)
    const tr = table.getElementsByTagName("tr")

    for (let i = 2; i < tr.length; i++) {
      const th = tr[i].getElementsByTagName("th")[0];
      const txtValue = th.innerText;
      if (txtValue.toLowerCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
  return (
    <details style={{ marginBottom: "3%" }}>
      <summary>Sets</summary>
      <div class="table-buttons">
        <button class="table-btn" id="table2-col1-btn" onClick={hideCols}>HashSet</button>
        <button class="table-btn" id="table2-col2-btn" onClick={hideCols}>Link HashSet</button>
        <button class="table-btn" id="table2-col3-btn" onClick={hideCols}>TreeSet</button>
      </div>
      <table id="table2" class="tg">
        <colgroup>
          <col id="header-vertical2" style={{ width: "20%" }} />
          <col id="hashset" />
          <col id="linkhashset" />
          <col id="treeset" />
        </colgroup>
        <thead>
          <tr>
            <th class="tg-fymr">Methods / DataStructures</th>
            <th class="tg-fymr">HashSet</th>
            <th class="tg-fymr">Link HashSet</th>
            <th class="tg-fymr">TreeSet</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th class="tg-fymr"><input id="table2-filterInput" onChange={filterTableRows} type="text" placeholder="search method" /></th>
            <td class="tg-fymr">Joule</td>
            <td class="tg-fymr">Joule</td>
            <td class="tg-fymr">Joule</td>
          </tr>
          <tr>
            <th class="tg-0pky">add</th>
            <td class="tg-hzcp">1.7749</td>
            <td class="tg-6zgs">1.4917</td>
            <td class="tg-is4z">1.4817</td>
          </tr>
          <tr>
            <th class="tg-0pky">addAll</th>
            <td class="tg-6zgs">1.4771</td>
            <td class="tg-hzcp">1.9335</td>
            <td class="tg-hqz3">1.5101</td>
          </tr>
          <tr>
            <th class="tg-0pky">clear</th>
            <td class="tg-is4z">1.0586</td>
            <td class="tg-hqz3">1.3288</td>
            <td class="tg-hzcp">1.8566</td>
          </tr>
          <tr>
            <th class="tg-0pky">contains</th>
            <td class="tg-hzcp">2.0685</td>
            <td class="tg-is4z">1.0401</td>
            <td class="tg-hzcp">2.0446</td>
          </tr>
          <tr>
            <th class="tg-0pky">containsAll</th>
            <td class="tg-is4z">1.4000</td>
            <td class="tg-hzcp">2.1748</td>
            <td class="tg-tj0w">1.4443</td>
          </tr>
          <tr>
            <th class="tg-0pky">iterateAll</th>
            <td class="tg-ybuk">1.4554</td>
            <td class="tg-is4z">1.2907</td>
            <td class="tg-hqz3">1.3844</td>
          </tr>
          <tr>
            <th class="tg-0pky">iterator</th>
            <td class="tg-hzcp">1.7596</td>
            <td class="tg-is4z">0,9613</td>
            <td class="tg-btii">1.7239</td>
          </tr>
          <tr>
            <th class="tg-0pky">remove</th>
            <td class="tg-ybuk">1.2633</td>
            <td class="tg-ybuk">1.2458</td>
            <td class="tg-is4z">1.0700</td>
          </tr>
          <tr>
            <th class="tg-0pky">removeAll</th>
            <td class="tg-hzcp">2.1359</td>
            <td class="tg-hqz3">1.9145</td>
            <td class="tg-is4z">1.3920</td>
          </tr>
          <tr>
            <th class="tg-0pky">retainAll</th>
            <td class="tg-6zgs">2.4092</td>
            <td class="tg-is4z">2.2512</td>
            <td class="tg-hzcp">3.2222</td>
          </tr>
          <tr>
            <th class="tg-0pky">toArray</th>
            <td class="tg-is4z">1.3833</td>
            <td class="tg-is4z">1.3776</td>
            <td class="tg-hzcp">1.6292</td>
          </tr>
        </tbody>
      </table>
    </details>
  )
}
